name: Deploy Docs
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.6.1"
      
      - name: Install latest Yarn
        run: corepack prepare yarn@3.5.0 --activate

      - name: Initialialize new project
        run: yarn init -2

      - name: Activate latest Yarn
        run: yarn set version stable

      - name: Install Node.js dependencies
        run: yarn install --immutable

      - name: Build
        run: yarn build

      - name: Deploy
        uses: reggionick/s3-deploy@v3
        with:
          folder: build
          bucket: ${{ secrets.S3_BUCKET }}
          bucket-region: ${{ secrets.S3_BUCKET_REGION }}
          invalidation: /
          delete-removed: true
          no-cache: true
          private: false
